[project]
profile = stylua

[stylua]
dockerfile = .dex/stylua.Dockerfile

[alias:format]
desc = Run formatter on all files.
cmd = find . -name "*.lua" -exec stylua {} \;

[neovim]
dockerfile = .dex/neovim.Dockerfile

[alias:create-dir]
desc = Create configuration directory.
cmd = mkdir -p ~/.config/nvim
hidden = true

[alias:cp-files]
desc = Copy configurations into configuration directory.
cmd = cp -r ./init.lua ./lua ~/.config/nvim
hidden = true

[alias:sync-install]
desc = Perform synchronous installation.
cmd = nvim +'SyncInstall' +qall
hidden = true

[alias:check]
desc = Check installation process.
pipeline = create-dir,cp-files,sync-install

[alias:package]
desc = Package configuration installation.
cmd = tar cvfz /workspace/neovim-config.tar.gz .local/share/nvim/ .config/nvim
workdir = /root/
hidden = true

[alias:artifact]
desc = Create installation artifact.
pipeline = create-dir,cp-files,sync-install,package
