name: default
type: docker
kind: pipeline

platform:
  os: linux
  arch: arm64
  
steps:
- name: Create PluginCache
  pull: never
  image: neovim
  commands:
  - echo "Install neovim configuration"
  - mkdir -p ~/.config/nvim
  - cp ./init.lua ~/.config/nvim/init.lua || exit 1
  - echo "Get packer"
  - git clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
  - echo "Install plugins"
  - nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerInstall'
  - echo "Archive cache"
  - cd ~
  - tar cvfz /tmp/PluginCache.tar.gz .local/share/nvim/ .config/nvim
  - echo "Upload archive"
  - echo "UPLOAD MISSING"
