name: default
type: docker
kind: pipeline

workspace:
  path: /drone/src

platform:
  os: linux
  arch: arm64
  
steps:
- name: Create artifact
  pull: never
  image: neovim
  commands:
  - echo "Setup init.lua"
  - mkdir -p ~/.config/nvim
  - cp ./init.lua ~/.config/nvim/init.lua || exit 1
  - echo "Setup packer"
  - git clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
  - echo "Install plugins"
  - nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerInstall'
  - echo "Create artifact"
  - cd ~
  - tar cvfz /drone/src/PluginCache.tar.gz .local/share/nvim/ .config/nvim
- name: Upload artifact
  pull: never
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: PluginCache.tar.gz
  checksum:
  - sha256
  - md5
  when:
    event: tag
    

