steps:
  check:
    image: tumbleowlee/neovim:latest

    commands:
      - mkdir -p ~/.config/nvim
      - cp -r ./init.lua ./lua ~/.config/nvim/ || exit 1
      - nvim +'SyncInstall' +qall || exit 1

    when:
      - event: push
      - event: manual

  artifact:
    image: tumbleowlee/neovim:latest

    commands:
      - mkdir -p ~/.config/nvim
      - cp -r ./init.lua ./lua ~/.config/nvim/ || exit 1
      - nvim +'SyncInstall' +qall || exit 1
      - export GIT_PATH=$(pwd)
      - cd ~/
      - tar cvfz $GIT_PATH/neovim-config.tar.gz .local/share/nvim/ .config/nvim

    when:
      - event: tag
        ref: refs/tags/nightly

  upload:
    image: woodpeckerci/plugin-github-release:latest

    settings:
      api_key:
        from_secret: github_token
      files: ./neovim-config.tar.gz
      title: 'neovim-config nightly'
      checksum:
        - sha256
        - md5

    when:
      - event: tag
        ref: refs/tags/nightly
