steps:
  check:
    image: alpine/neovim:latest
    commands:
      - mkdir -p ~/.config/nvim
      - cp ./init.lua ~/.config/nvim/init.lua || exit 1
      - git clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
      - nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
      - nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerInstall'
    when:
      - event: tag
        ref: refs/tags/nightly
      - event: push
  artifact:
    image: alpine/neovim:latest
    commands:
      - export GIT_PATH=$(pwd)
      - tar cvfz $GIT_PATH/neovim-config.tar.gz .local/share/nvim/ .config/nvim
    when:
      - event: tag
        ref: refs/tags/nightly
  upload:
    image: woodpeckerci/plugin-github-release:latest
    settings:
      api_key:
        from_secret: github_token
      files: ./neovim-config.tar.gz
      title: 'neovim-config nightly'
      checksum:
        - sha256
        - md5
    when:
      - event: tag
        ref: refs/tags/nightly
